[package]
name = "ReprRustSourceBasedCoverage"
version = "0.1.0"
authors = ["Jozef Holl√Ω <j2.00ghz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
